In [78]:
import pandas as pd

In [50]:
ch89dg = pd.read_csv('./cleaned_data/CH89DG.csv')
ch89m = pd.read_csv('./cleaned_data_descriptive/ch89m.csv')
ch89pru = pd.read_csv('./cleaned_data/ch89pru.csv')
ch89q = pd.read_csv('./cleaned_data/ch89q.csv')

In [140]:
ch89m_model

m005_ALL35_69  m008_MEDICALc  m065_STROKEc  m023_ALLCAc  m059_ALLVASCc  \
0            15.08          13.98        193.02         6.13           2.50   
1             7.49           6.91        122.77         2.75           1.61   
2            11.29          10.45        157.90         4.44           2.06   
3            15.37          14.45        196.62         6.07           2.43   
4             8.27           7.64        131.42         2.92           1.71   
..             ...            ...           ...          ...            ...   
196          13.94          13.39        237.08         3.56           3.82   
197          18.88          17.63        223.03         4.96           3.88   
198          24.37          22.51        599.82         9.12           7.78   
199          11.52          11.39        208.17         4.77           2.89   
200          17.95          16.95        404.00         6.94           5.33   

     m028_OESOPHCAc  m072_COPDc  m010_NONMEDc county sex  xiang  
0            166.66      333.19        110.50     AA   M      3  
1             62.46      124.03         58.77     AA   F      3  
2            114.56      228.61         84.64     AA   T      3  
3            166.30      352.14         92.30     AB   M      3  
4             57.80      135.77         62.97     AB   F      3  
..              ...         ...           ...    ...  ..    ...  
196          216.23      217.77         54.82     XB   F      3  
197          314.56      353.98        125.30     XB   T      3  
198          204.30      456.50        186.19     YA   M      3  
199          127.31      204.53         12.94     YA   F      3  
200          165.81      330.51         99.56     YA   T      3  

[201 rows x 11 columns]

In [141]:
ch89m_model.loc[ch89m_model.county.isna(), 'county'] = 'NA'

In [16]:
questions_list

Unnamed: 0 question
0             0     q010
1             1     q015
2             2     q016
3             3     q022
4             4     q023
..          ...      ...
133         133     q237
134         134     q238
135         135     q239
136         136     q240
137         137     q241

[138 rows x 2 columns]

###### merge tables

In [19]:
mortality_list = pd.read_csv('./cleaned_data_descriptive/mortality_list.csv')
mortality_list

Unnamed: 0 mortality_targets
0           0     m005_ALL35_69
1           1     m008_MEDICALc
2           2      m065_STROKEc
3           3       m023_ALLCAc
4           4     m059_ALLVASCc
5           5    m028_OESOPHCAc
6           6        m072_COPDc
7           7      m010_NONMEDc

In [51]:
m_targets = pd.read_csv('./cleaned_data_descriptive/mortality_list.csv')
m_targets = m_targets['mortality_targets']
list(m_targets.values)

['m005_ALL35_69',
 'm008_MEDICALc',
 'm065_STROKEc',
 'm023_ALLCAc',
 'm059_ALLVASCc',
 'm028_OESOPHCAc',
 'm072_COPDc',
 'm010_NONMEDc']

In [66]:
questions = pd.read_csv('./cleaned_data_descriptive/questions_list.csv')
questions = questions['question']
questions
m_targets = pd.read_csv('./cleaned_data_descriptive/mortality_list.csv')
m_targets = m_targets['mortality_targets']
dg_to_keep = ['d005','d006','d007','d008','d009', 
               'd012','d013','d014','d015','d016', 
               'd028','d029','d030','d031','d032','d033','d034','d035','d036', 
               'd037','d038','d039','d040', 
               'd041','d042','d043','d044','d045','d046', 
               'd047','d048','d049','d050','d051','d052', 
               'g001','g002','g003','g004','g005']
ch89q_model = ch89q.loc[:,list(questions) + ['county', 'sex', 'xiang'] ]
ch89dg_model = ch89dg.loc[:,list(dg_to_keep) + ['county', 'sex', 'xiang']]
ch89m_model = ch89m.loc[:,list(m_targets.values) + ['county', 'sex', 'xiang']] 

In [71]:

    
bat = pd.merge(ch89q_model, ch89dg_model, 
               how='left',
              left_on=['county', 'sex', 'xiang'],
              right_on=['county', 'sex', 'xiang'])
bat = pd.merge(bat, ch89m_model,
               how='left',
              left_on=['county', 'sex', 'xiang'],
              right_on=['county', 'sex', 'xiang'])
bat = pd.merge(bat, ch89pru,
               how='left',
              left_on=['county', 'sex', 'xiang'],
              right_on=['county', 'sex', 'xiang'])



In [73]:
bat.shape

(621, 297)

In [70]:
bat

q010  q015  q016  q022  q023  q024  q025    q037   q038    q039  ...  \
0     NaN   NaN   NaN   3.3   NaN   NaN   NaN     NaN    NaN     NaN  ...   
1     NaN   NaN   NaN  10.0   NaN   NaN   NaN     NaN    NaN     NaN  ...   
2     NaN   NaN   NaN   6.7   NaN   NaN   NaN     NaN    NaN     NaN  ...   
3     NaN   NaN   NaN   0.0   NaN   NaN   NaN     NaN    NaN     NaN  ...   
4     NaN   NaN   NaN   0.0   NaN   NaN   NaN     NaN    NaN     NaN  ...   
..    ...   ...   ...   ...   ...   ...   ...     ...    ...     ...  ...   
616   NaN   NaN   NaN   0.0   NaN   NaN   NaN     NaN    NaN     NaN  ...   
617   NaN   NaN   NaN   0.0   NaN   NaN   NaN     NaN    NaN     NaN  ...   
618   0.0  70.0  85.0   NaN  16.7  46.7  35.0  7149.0  142.0  2142.0  ...   
619   0.0  70.0  85.0   NaN  28.3  58.3  11.7  7327.0   25.0   980.0  ...   
620   0.0  70.0  85.0   1.7  22.5  52.5  23.4  7238.0   84.0  1561.0  ...   

     g004  g005  m005_ALL35_69  m008_MEDICALc  m065_STROKEc  m023_ALLCAc  \
0     NaN   NaN            NaN            NaN           NaN          NaN   
1     NaN   NaN            NaN            NaN           NaN          NaN   
2     NaN   NaN          15.08          13.98        193.02         6.13   
3     NaN   NaN            NaN            NaN           NaN          NaN   
4     NaN   NaN            NaN            NaN           NaN          NaN   
..    ...   ...            ...            ...           ...          ...   
616   NaN   NaN            NaN            NaN           NaN          NaN   
617   NaN   NaN          11.52          11.39        208.17         4.77   
618   NaN   NaN            NaN            NaN           NaN          NaN   
619   NaN   NaN            NaN            NaN           NaN          NaN   
620   3.0   2.0          17.95          16.95        404.00         6.94   

     m059_ALLVASCc  m028_OESOPHCAc  m072_COPDc  m010_NONMEDc  
0              NaN             NaN         NaN           NaN  
1              NaN             NaN         NaN           NaN  
2             2.50          166.66      333.19        110.50  
3              NaN             NaN         NaN           NaN  
4              NaN             NaN         NaN           NaN  
..             ...             ...         ...           ...  
616            NaN             NaN         NaN           NaN  
617           2.89          127.31      204.53         12.94  
618            NaN             NaN         NaN           NaN  
619            NaN             NaN         NaN           NaN  
620           5.33          165.81      330.51         99.56  

[621 rows x 189 columns]

###### clustering analysis

In [74]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [77]:
km = KMeans()
ss = StandardScaler()

In [150]:
ch89m_model.loc[ch89m_model['sex'] == 'T',]

m005_ALL35_69     0
m008_MEDICALc     0
m065_STROKEc      0
m023_ALLCAc       0
m059_ALLVASCc     0
m028_OESOPHCAc    0
m072_COPDc        0
m010_NONMEDc      0
county            0
sex               0
xiang             0
dtype: int64

In [147]:
ch89m_model.loc[ch89m_model['sex'] == 'T',]['county']

2      AA
5      AB
8      AC
11     BA
14     BB
       ..
188    WB
191    WC
194    XA
197    XB
200    YA
Name: county, Length: 67, dtype: object

In [123]:
bat_km[]

(207, 297)

In [163]:
bat.shape

(621, 297)

In [177]:
bat_km = bat[(bat['sex'] == 'T') & (bat['xiang'] == 3)]
# bat_km.dropna(axis = 0, thresh=150)
# sum(bat_km.isna().sum().sort_values(ascending=False) <100)
bat_km.shape
bat_km.county
bat_km.isna().sum().sort_values(ascending=False).describe()
bat_km = bat_km.dropna(axis=1)
bat_km.isna().sum().describe()
bat_km.columns

Index(['q010', 'q015', 'q016', 'q022', 'q023', 'q024', 'q025', 'q037', 'q038',
       'q039',
       ...
       'r017', 'r018', 'r019', 'r020', 'r021', 'r022', 'r023', 'r024', 'r025',
       'r026'],
      dtype='object', length=193)

In [178]:
bat_km_sc = ss.fit_transform(bat_km.select_dtypes(exclude = 'object'))

In [180]:
km = KMeans(n_clusters=3)
km.fit(bat_km_sc)

KMeans(n_clusters=3)

In [181]:
km.cluster_centers_

array([[-1.20638548e-01, -3.39330490e-02,  1.47613623e-01,
         3.93717877e-01, -6.74926354e-01,  6.42189268e-01,
         2.01631402e-01,  4.86137456e-01,  8.00937749e-01,
         1.10270268e+00, -1.47518352e-01,  6.17487105e-02,
         7.73204222e-02,  1.19553723e-01,  3.85456949e-03,
        -5.08555894e-01,  1.84427483e-01, -4.04945267e-01,
        -8.26646955e-01, -1.01304559e+00,  4.50038756e-01,
         4.45333237e-01, -2.45355516e-01, -4.60785745e-01,
        -4.17017092e-01, -1.07036417e-01, -3.49947584e-01,
        -4.39954159e-01, -6.12211445e-01, -3.85448569e-01,
        -2.55162977e-01, -6.81406027e-01, -6.80119891e-01,
        -4.18616563e-01, -4.69049505e-01, -3.61200725e-01,
        -5.50951665e-01, -4.76097250e-01,  5.19675901e-01,
        -1.07482133e-01,  3.55856771e-01, -6.61129039e-02,
        -3.04788253e-01, -4.11069259e-01, -4.34436303e-01,
        -5.67495858e-01,  1.37086260e-01, -1.37500576e-01,
        -1.19011627e-01, -1.99288930e-01,  2.12311970e-0

In [182]:
km.labels_

array([2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1], dtype=int32)

In [185]:
from sklearn.metrics import silhouette_score


In [191]:
# code from GA lesson 39 k_means
scores = []

for k in range(2, 5):
    km = KMeans(n_clusters = k)
    km.fit(bat_km_sc)
    inertia = km.inertia_
    silhouette = silhouette_score(bat_km_sc, km.labels_)
    scores.append([k, inertia, silhouette])

score_df = pd.DataFrame(scores, columns = ['k', 'inertia', 'silhouette'])
score_df

k       inertia  silhouette
0  2  11600.388242    0.115461
1  3  10627.468550    0.088429
2  4   9919.415090    0.092072

In [193]:
import numpy as np

In [197]:
# This code reads the text file with all the code descriptions as a single column and 
# will return a df. The last bits will match the imported text file to the features with an 
# importance > 0
# After the initial modeling:

with open('./data/CHNAME.txt', 'r') as file:
    data = file.read()
    rows = data.split('\n')

descriptions = pd.DataFrame(rows)

text_df = descriptions.iloc[::2,:]
text_df['code'] = text_df[0].str.split(expand=True).iloc[:,0]
text_df.rename(columns={0:'description'}, inplace=True)
text_df['code'] = text_df['code'].str.lower()
text_df

/var/folders/7q/63cgxnn50sl5zwxkchv_j2cr0000gn/T/ipykernel_4681/1765311509.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text_df['code'] = text_df[0].str.split(expand=True).iloc[:,0]
/var/folders/7q/63cgxnn50sl5zwxkchv_j2cr0000gn/T/ipykernel_4681/1765311509.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text_df.rename(columns={0:'description'}, inplace=True)
/var/folders/7q/63cgxnn50sl5zwxkchv_j2cr0000gn/T/ipykernel_4681/1765311509.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_in

description  code
0     M001 ALL0-4     mortality ALL CAUSES AGE 0-4 (...  m001
2     M002 ALL5-14    mortality ALL CAUSES AGE 5-14 ...  m002
4     M003 ALL15-34   mortality ALL CAUSES AGE 15-34...  m003
6     M004 ALL0-34    mortality ALL CAUSES AGE 0-34 ...  m004
8     M005 ALL35-69   mortality ALL CAUSES AGE 35-69...  m005
...                                                 ...   ...
1268  Q243 fWTadj     questionnaire WEIGHT OF SCHOOL...  q243
1270  Q244 fHT        questionnaire HEIGHT OF SCHOOL...  q244
1272  Q245 fHTadj     questionnaire HEIGHT OF SCHOOL...  q245
1274  Q246 fBMI       questionnaire WEIGHT/HEIGHT**2...  q246
1276  Q247 fBMIadj    questionnaire WEIGHT/HEIGHT**2...  q247

[639 rows x 2 columns]

k-means doesn't offer much of value here.

In [198]:
from sklearn.cluster import DBSCAN

In [232]:
dbscan = DBSCAN(eps = 11, min_samples=2)
dbscan.fit(bat_km_sc)
silhouette_score(bat_km_sc, dbscan.labels_)
dbscan.labels_

array([-1,  0,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1,  0,  0, -1,  1,  1, -1, -1, -1, -1, -1, -1,  2, -1,  2,
       -1, -1, -1, -1, -1, -1,  3, -1, -1,  3,  4, -1,  4, -1, -1, -1, -1,
       -1, -1, -1, -1,  5,  5, -1,  5, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1])

In [228]:
list(bat_km.columns)

['q010',
 'q015',
 'q016',
 'q022',
 'q023',
 'q024',
 'q025',
 'q037',
 'q038',
 'q039',
 'q040',
 'q082',
 'q083',
 'q084',
 'q087',
 'q088',
 'q089',
 'q090',
 'q091',
 'q092',
 'q093',
 'q094',
 'q095',
 'q096',
 'q097',
 'q098',
 'q099',
 'q100',
 'q101',
 'q102',
 'q103',
 'q104',
 'q105',
 'q106',
 'q107',
 'q108',
 'q109',
 'q110',
 'q119',
 'q120',
 'q121',
 'q122',
 'q123',
 'q124',
 'q125',
 'q126',
 'q127',
 'q128',
 'q129',
 'q136',
 'q137',
 'q140',
 'q141',
 'q144',
 'q145',
 'q146',
 'q147',
 'q148',
 'q149',
 'q150',
 'q151',
 'q152',
 'q153',
 'q154',
 'q155',
 'q156',
 'q157',
 'q158',
 'q159',
 'q160',
 'q161',
 'q162',
 'q163',
 'q164',
 'q165',
 'q166',
 'q167',
 'q168',
 'q169',
 'q170',
 'q171',
 'q172',
 'q173',
 'q174',
 'q175',
 'q176',
 'q177',
 'sex',
 'xiang',
 'd005',
 'd006',
 'd007',
 'd008',
 'd009',
 'd012',
 'd013',
 'd014',
 'd015',
 'd016',
 'd028',
 'd029',
 'd030',
 'd031',
 'd032',
 'd033',
 'd034',
 'd035',
 'd036',
 'd037',
 'd038',
 'd039',
 

adjusting the eps parameter did not reveal anything useful. The best silhouette score for .24 was seen with min_samples = 1, eps = 18.  

spectral implementation from [source](https://www.youtube.com/watch?v=YHz0PHcuJnk)

In [237]:
from sklearn.preprocessing import normalize
from scipy import linalg
import matplotlib.pyplot as plt

In [262]:
U, sigma, _ = linalg.svd(bat_km_sc, full_matrices=False, lapack_driver='gesvd')

Usubset = U[:,0:2]
y_pred_sc = KMeans(n_clusters=2).fit_predict(normalize(Usubset))

y_pred_sc
# Usubset

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0], dtype=int32)

In [261]:
silhouette_score(bat_km_sc,y_pred_sc)

0.05664362916161154